version: "3.9"

services:
  web:
    build: .
    command: uvicorn downloader.api:app --host 0.0.0.0
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A downloader.tasks worker --concurrency=5 --loglevel=info
    environment:
      - PUSHOVER_USER=xxx # remove the environment section if you
      - PUSHOVER_TOKEN=xxx # don't have pushover creds
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - .:/app
      - /Volumes/Goodz:/Goodz
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
